### ISSUE TITLE
Cannot compile Arduino code to 32u416m board

### ISSUE THREAD

**Issue by Michael-Longley** [Free-Brick-Studio/Bricxer#27]
When compiling our code for the Elite C / Pro Micro controllers we are getting the following errors.

```
.platformio\packages\framework-arduino-avr\cores\arduino\USBCore.cpp:73:29: error: 'USB_VID' was not declared in this scope
Compiling .pio\build\32u416m\FrameworkArduino\main.cpp.o
  D_DEVICE(0xEF,0x02,0x01,64,USB_VID,USB_PID,0x100,IMANUFACTURER,IPRODUCT,ISERIAL,1); 

.platformio\packages\framework-arduino-avr\cores\arduino\USBCore.cpp:73:37: error: 'USB_PID' was not declared in this scope
  D_DEVICE(0xEF,0x02,0x01,64,USB_VID,USB_PID,0x100,IMANUFACTURER,IPRODUCT,ISERIAL,1);
```
These errors can be seen by building the C++ code using PlatformIO in VSCode.

Research if this is a configuration issue, a known issue with the Arduino libraries or if we can circumvent / resolve it.

**Comment by mjschuetze102** [comment]
I don't feel like reading tonight, but https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758039 might have a solution.

**Comment by mjschuetze102** [comment]
Also, this may help: https://github.com/platformio/platformio-core/issues/164

**Comment by mjschuetze102** [comment]
https://electronics.stackexchange.com/questions/44577/arduino-leonardo-in-eclipse-vid-and-pid-missing

**Comment by Michael-Longley** [comment]
The solution to this is to add `#define USB_VID <Our VID>` and `#define USB_PID <Our PID>` to `C:/Users/<Your User>/.platformio/packages/framework-arduino-avr/cores/arduino/USBCore.h`. We still need to pick a PID and a VID but that will be simple so I will open an issue to decide that and add the checks for it in `ControllerConnection.py`.
